# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest Test Automation

on:
  push:
    branches: [ "main", "milestone/**" ]
  pull_request:
    branches: [ "main", "milestone/**" ]

jobs:
  run-jest-tests:
    permissions: write-all
    name: Jest Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
  
    - name: Install all dependencies
      run: yarn install

    - name: Run Jest Tests
      run: yarn test | tee ./coverage.txt && exit ${PIPESTATUS[0]}

    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-path: ./coverage.txt
